-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 
-- 대여 금액(컬럼명: FEE) 리스트를 출력하는 SQL문
-- ROUND(DAILY_FEE * 30 * ((100-DISCOUNT_RATE)/100))

SELECT R.CAR_ID, R.CAR_TYPE, ROUND(DAILY_FEE * 30 * ((100-DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR R JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON R.CAR_TYPE = P.CAR_TYPE
WHERE R.CAR_TYPE IN ('세단', 'SUV') AND P.DURATION_TYPE = '30일 이상' 
        AND R.CAR_ID NOT IN (SELECT CAR_ID 
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                            WHERE START_DATE <='2022-11-30' AND END_DATE>='2022-11-01')
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2 ASC, 1 DESC