-- 코드를 입력하세요
-- 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
-- 이때 결과는 음식 종류를 기준으로 내림차순 정렬해주세요.


SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R1
WHERE FAVORITES = (SELECT MAX(FAVORITES) FROM REST_INFO R2 WHERE R1.FOOD_TYPE = R2.FOOD_TYPE GROUP BY FOOD_TYPE)
ORDER BY 1 DESC