-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, 
       ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I 
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID  -- [핵심 수정] 식당 아이디별로 그룹을 지어야 합니다.
ORDER BY SCORE DESC, I.FAVORITES DESC