SELECT D.PRODUCT_ID, D.PRODUCT_NAME, SUM(D.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT D JOIN FOOD_ORDER O ON D.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY  D.PRODUCT_ID, D.PRODUCT_NAME
ORDER BY 3 DESC, 1